CMU-Perceptual-Computing-Lab/openpose

3rdparty/caffe/python/caffe/__init__.py

PyCaffe can't be found as a module in PYTHONPATH due to the misssing __init__.py file. I added it from caffe_rtpose.

Add missing __init__.py to fix pycaffe import.

---

ubuntu/install_caffe_and_openpose_if_cuda8.sh

Fixed the execution path in the script function `executeShInItsFolder` and command line.

Fixed script execution path

---

3rdparty/caffe/install_caffe_if_cuda8.sh

The current lowercase -h followed by an argument specifies a hostname.

Fix pip command

---

src/openpose/face/faceExtractor.cpp
src/openpose/hand/handExtractor.cpp
windows/OpenPose/OpenPose.vcxproj
windows/OpenPose/OpenPose.vcxproj.filters

Fix compilation on Windows/VS 2015
- Missing cast
- Missing OpenCV face detection files

Fix windows compilation

---

README.md

Link was broken in the markdown

Fixed link to library_add_new_module

---

include/openpose/headers.hpp

global includes has duplicates

fix global includes of tracking module

---

examples/tutorial_api_python/01_body_from_image.py
examples/tutorial_api_python/02_whole_body_from_image.py
examples/tutorial_api_python/04_keypoints_from_images.py
examples/tutorial_api_python/05_keypoints_from_images_multi_gpu.py
examples/tutorial_api_python/06_face_from_image.py
examples/tutorial_api_python/07_hand_from_image.py
examples/tutorial_api_python/08_heatmaps_from_image.py
examples/tutorial_api_python/09_keypoints_from_heatmaps.py
python/openpose/openpose_python.cpp

Python fix

---

doc/prerequisites.md

It should be runfile instead of runtime. It annoys me a little bit when I see that.

Fixed a tiny typo

---

doc/faq.md

Fixed a typo in faq.md

---

doc/installation.md

Fix a typo in installation.md

---

src/openpose/filestream/videoSaver.cpp

Add quotes to pathname arguments for `ffmpeg` and `mv` command in videoSaver.cpp

---

doc/modules/calibration_module.md

Fix a typo in calibration_module.md

Fix a typo in calibration_module.md

---

examples/tutorial_api_python/09_keypoints_from_heatmaps.py

fix   openpose/examples/tutorial_api_python/09_keypoints_from_heatmaps.py

fix python examples_09

---

doc/README.md

Hyperlink fix for Output Information

Quick fix of a simple typo

---

doc/README.md

Typos fix in readme

---

doc/installation/1_prerequisites.md

Please correct the statement, it is just necessary to deactivate conda, rather than uninstalling it. Even compiling Caffe will cause errors because of the conda environment.

Correction about anaconda in Ubuntu

---

doc/installation/1_prerequisites.md

Fixed typo in installation doc ('brom' --> 'from')

fixed typo in doc

---

doc/advanced/3d_reconstruction_module.md

Link broken when trying to setup 3d module for openpose, fixed!
Might have more...

Link fix in 3d module installation guide

---

doc/installation/0_index.md

This commit adds a note on how to install openpose via cli without GPU unit.

Improve docs on CPU_ONLY mode #2037

---

doc/10_community_projects.md

The previous repository, i.e., [ildoonet/ros-openpose](https://github.com/ildoonet/ros-openpose), seems dead. So, instead of adding the new repository, i.e., [ravijo/ros_openpose](https://github.com/ravijo/ros_openpose) in this commit, I updated the previous one.
I hope this pull request should be acceptable. Or else, let me know the proper way!
Thanks

Add ravijo/ros_openpose. Read description, please.

---

doc/10_community_projects.md

Here's a project I made so that I could get 3D keyframes using just a single Intel RealSense camera. Feel free to use it in your own projects (with due credit) and please feel free to contribute to it. I need all the help I can get to optimize it. Enjoy.

Add RealSense2OpenPose3D Project Link

---

doc/09_authors_and_contributors.md

- Fixed a minor grammatical error in the doc/09_authors_and_contributors.md file.

Fixed typo and doc mistake
