doc/demo_overview.md

I've found `--start_gpu` argument is incorrectly specified as GPU device start number in doc/demo_overview.md.
According to `$./build/examples/openpose/rtpose.bin --help`, `--num_gpu_start` is correct argument, isn't it?

fix argument inconsistency

---

src/openpose/filestream/cocoJsonSaver.cpp

COCO challenge only has 17 keypoints, so indexesInCocoOrder.size()==17.
openpose added the neck keypoint (index 1), therefore numberBodyParts==18.
numberBodyParts-1==17, Statement `if (bodyPart < numberBodyParts-1)` adds a comma for  every bodyPart ([0..16]), add a extra comma in the end, causing a bad json format file, which can not be proporly parsed.

fix wrong json file format

---

doc/demo_overview.md

part_to_show only goes on till 40 for COCO pairs, not 69, because there are 19 pairs for COCO. Gives an error when you set `--part_to_show` beyond 40 @gineshidalgo99

Typo in part_to_show description

---

doc/output.md

Fixed a broken link on the following page.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md

Fixed link in doc/output.md

---

examples/tutorial_pose/2_extract_pose_or_heatmat_from_image.cpp

Getting Non valid scaleNetToOutput:
if (scaleNetToOutput == -1.f)
error("Non valid scaleNetToOutput.", __LINE__, __FUNCTION__, __FILE__);
std::pair<int, std::string> PoseGpuRenderer::renderPose(Array<float>& outputData,
const Array<float>& poseKeypoints,
const float scaleInputToOutput,
const float scaleNetToOutput)
expects 4 parameter.

Fix Error: Non valid scaleNetToOutput.

---

CMakeLists.txt

Error message: string sub-command REPLACE requires at least four arguments.
CMake 3.10.1

CMake string arguments error

---

src/openpose/core/datum.cpp

Fixing small bug in cloning `handRectangles` in `Datums`.

fix datum clone handrectangles bug

---

include/openpose/pose/poseRenderer.hpp

I could not find why this started to be a problem but since May the 4th I get compilation errors due to the missing map.
```
poseRenderer.hpp:22:20: error: ‘map’ in namespace ‘std’ does not name a template type
const std::map<unsigned int, std::string> mPartIndexToName;
^
```

include std::map in poseRenderer.hpp

---

cmake/OpenPoseConfig.cmake.in

Fixed the issue "No such file or directory" When using openpose as an external library via cmake. Altered the library path in OpenPoseConfig.cmake.in.
For reference see issue #814

fixed issue #814

---

python/openpose/openpose.py

ensure output size passed to cv2.warpAffine() is always a couple of integers

cv2.warpAffine() int() the floats for output image size

---

include/openpose/pose/poseRenderer.hpp
src/openpose/pose/poseRenderer.cpp

This allows poseGpuRenderer and poseCpuRenderer to release their resources when using only poseRenderer as an interface.

Added virtual destructor to base poseRenderer header

---

src/openpose/core/keepTopNPeople.cpp

This fixes a bug where the volume of of the peopleArray was being used instead of size of the first dimension. `getVolume()` returns all dimensions multiplied by each other, so for a `personArray` with a single person (using the BODY_25 model) `getVolume()` will return 75 (1 * 25 * 3) whereas `getSize(0)` will return 1 which is what needs to be compared to the `mNumberPeopleMax`, a variable containing the number of people to allow. 
The bug would manifest itself as an array out of bounds error on line 39 `poseScoresSorted[mNumberPeopleMax-1];` ,which assumes that there are always more people in the `peopleArray` than `mNumberPeopleMax`, which is not always the case because of the error (using volume instead of size) in the guard above.

Fix bug in KeepTopNPeople

---

ubuntu/install_cuda.sh
ubuntu/install_cudnn.sh

When calling the script on a default install Ubuntu 16.04 it will error
out with
ubuntu/install_cuda.sh: 3: ubuntu/install_cuda.sh: [[: not found
With a shebang we will get full bash functionality.

use bash shebang in cuda installation script

---

python/openpose/_openpose.cpp

A [recent commit](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/dcc0c51348f29eeb468a0f6df764ded66e84a8bb) changed the `getPoseMaxPeaks` interface, breaking the python module and causing linking to fail in the final steps of `make`. This PR fixes it to use the new, unparameterized interface, allowing linking to properly complete.

Fix call to getPoseMaxPeaks

---

CMakeLists.txt

This allows for the ability to handle Protobuf versions more flexibly. 
I'm currently am on Ubuntu 18.04 which has Protobuf 3.0.0 as a base system requirement of a few other packages. When building OpenPose I have a separate build of Protobuf (version 3.6.0) that's compliant with the version of Tensorflow (version 1.12.0) that's also being built. This adds the ability to direct the OpenPose build to use the non-system installed Protobuf, which is already the case for Caffe, OpenCV, and Tensorflow.
If this isn't the correct way to handle this then let me know and I'll rework it. If you decide it's not appropriate please let me, I'll need to replace the main system's protobuf.
Thanks.

Include the handling of Protobuf, who's includes are transitively required via Caffe, in the build.

---

CMakeLists.txt

Fixes CMake  typo `if (NOT A) ... endif(A)`.
Fixes missing-GLU build fail.
OpenGL package was not searched for + on Ubuntu 16.04, after `find_package(OpenGL ...)` `OPENGL_INCLUDE_DIRS` is empty while `OPENGL_INCLUDE_DIR` contains the path to `GL.h`, `GLU.h` etc.

Patch1 opengl

---

src/openpose/3d/cameraParameterReader.cpp

This allows the build against both OpenCV 3 and OpenCV 4.
cv::initUndistortRectifyMap was moved from imgproc.hpp to calib3d.hpp.

Allow build against OpenCV 4.

---

doc/installation.md

Because `3rdparty/scripts/...` does not exist anymore

Update installation instruction for Ubuntu

---

src/openpose/3d/poseTriangulation.cpp

- Substituted a "break" with a "continue" so that if the reprojection error does not change removing camera "k" it keeps on exploring with camera "k+1" and so on.
- Returns new bestReprojectionError after removing the k-th camera

Fix in multi-view (camera Leave One Out)

---

include/openpose/wrapper/wrapperAuxiliary.hpp

The variable `userInputAndPreprocessingWsEmpty` but only checks if `userInputWs` is empty, and not `userPreProcessingWs`. This results is premature termination during sanity checks at [wrapperAuxiliary.cpp:115](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/wrapper/wrapperAuxiliary.cpp#L115) in some scenarios.
For example: The user wants to do hand pose extraction using their own hand rectangles. They use the default producer but supply their own hand rectangles with a pre-processor worker. The above sanity check will erroneously fail, even though hand rectangles are supplied. I can provide code for a minimal repro if needed.

Fix sanity check in wrapper

---

doc/installation.md

The 1st link I, nxb, clicked didn't work. (the aforementioned 1st link: https://github.com/esemeniuc/openpose-docker)
`docker pull docker pull exsidius/openpose`, on the other hand, worked flawlessly!  This commit was written on Thursday September  5, 2019.  The author cannot promise it will still be true at future times.

Update installation.md to quickstart Linux users

---

doc/installation.md
doc/prerequisites.md

prerequisites.md
- sudo across all apt commands in ubuntu
- bump cudnn 7.2 -> 7.5 for 18.04 to get on par with current
installation.md
- `nproc` is not available on MacOS, uses `sysctl -n hw.logicalcpu` to return logical cores instead

Command consistency checks and error fixing in mac build instructions

---

doc/installation.md
examples/user_code/README.md
scripts/travis/run_make.sh

Upon further coding proceeds, found another unsquashed macos unavailable nproc.
Decreases travis build time too!
Fix last pr that uses the wrong command of phy cores instead of logical cores.

Changes nproc for mac to hw.logicalcpu where applicable

---

doc/prerequisites.md

By using the default instructions, `make install` requires `sudo` to install the files into `/usr/local/bin/` thus the change or it will fail.
But to have the next instructions' path`{CMAKE_FOLDER_PATH}` to be applicable , either `bootstrap --prefix=<dir>` is needed instead of a one-liner `./boostrap &&...` or just to not using `make install` and using the built cmake under `<make dir>/bin` directly.

sudo added at make install in Ubuntu. Also nproc.

---

doc/installation_jetson_tx2_jetpack3.3.md

Installation instructions to build Python 2.7

---

include/openpose_private/utilities/openCvMultiversionHeaders.hpp

In old versions, variables like `CV_IMWRITE_JPEG_QUALITY` are "enum"s not "define"s. Hence, "ifdef"s here are useless here and will make OpenCV4.0+(non-alpha/beta version) not able to compile. This can be fixed by detecting the macro `cvvConvertImage` which is along with CV_LOAD_xxx & CV_IMWRITE_xxx in old versions :)
[#1439](https://github.com/CMU-Perceptual-Computing-Lab/openpose/pull/1439) noticed the question as well, but his PR seems to be "OpenCV4-only". According to your original codes in `openCvMultiversionHeaders.hpp`, I fixed it by detecting the macro `cvvConvertImage`. And it compiled finally. Thx.

Macro issue in `openCvMultiversionHeaders.hpp` that makes CV4+ not compatible

---

scripts/osx/install_deps.sh

homebrew/science is now deprecated, but opencv and hdf5 are now both in homebrew/core, so can be installed without tapping homebrew/science.

Don't try to tap homebrew/science

---

doc/installation.md

To use OpenPose via docker, you need to install two dependencies on nvidia.
[Guide](https://github.com/gormonn/openpose-docker/blob/master/README.md)

Add link to guide how to use exsidius/openpose docker image

---

doc/prerequisites.md

OpenSSL does not come preinstalled in a fresh Ubuntu 18.04 install, so we'll need to get `libssl-dev` for it.

Added OpenSSL for fresh Ubuntu 18.04 installation

---

CMakeLists.txt

Issue: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1575
Fix the wrong change made by "commit 6b3652bed2a4dcefd574bccb297e0c79619e2faf"  which leads to custom caffe path setting at UNIX OR APPLE been broken.
Recover the wrong change in the bug part, and it works well on linux now.

fix a bug in "CMakeLists.txt" which causes pre-built Caffe path setting fail on UNIX or APPLE

---

src/openpose/core/arrayCpuGpu.cpp

In Openpose repository, Caffe wrapper implementations of three functions have copy-paste error and they are fixed.

Caffe wrapper functions have copy-paste error on implementation

---

scripts/ubuntu/install_cuda.sh

CUDA installation has failed for Ubuntu 20.04 and unfortunately has to be continued with manual steps. So, the script is updated for CUDA 11 for Ubuntu 20.x versions to download automatically.

Update script for downloading CUDA 11 for Ubuntu 20 or later versions

---

CMakeLists.txt

Since the server for models and 3rd party libraries is temporarily not available now, I wonder if it would be helpful to add a mirror option to `CMakeLists.txt` so that CMake can download them from another site.

Add a mirror option to CMakeLists.txt

---

examples/tutorial_api_python/01_body_from_image.py
examples/tutorial_api_python/02_whole_body_from_image.py
examples/tutorial_api_python/04_keypoints_from_images.py
examples/tutorial_api_python/05_keypoints_from_images_multi_gpu.py
examples/tutorial_api_python/06_face_from_image.py
examples/tutorial_api_python/08_heatmaps_from_image.py
examples/tutorial_api_python/09_keypoints_from_heatmaps.py
examples/tutorial_api_python/12_asynchronous_custom_output.py
examples/tutorial_api_python/openpose_python.py
python/openpose/openpose_python.cpp

Currently AsynchronousOut mode won't work with the Python API since it is not possible to get ahold of a Datum created inside OpenPose from the Python side. The reason for this is at the moment, lists are copied when going over the Python => C++ boundary. See https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#making-opaque-types . To get the semantics of passing a mutable reference, we can wrap an STL type.
Unfortunately this is not quite sufficient. We need to pass a shared_pointer<vector<shared_pointer<datum>>> to `openpose::Wrapper`. The outer shared pointer is eventually pointed somewhere else in `queue.hpp`:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/3915b922eb345de9d788cb46541d42641aa014c4/include/openpose/thread/queue.hpp#L73
So we just swap that …

Improve Python API including enabled AsynchronousOut mode

---

doc/installation/README.md
doc/installation/prerequisites.md

When I tried to install OpenPose with the installation instructions in `doc/installation/README.md`, I found that most links are not pointing to the right urls. It seems that many `.md` files are moved from `doc/installation/` to `doc/`. I fixed the links in `doc/installation/README.md` and `doc/installation/prerequisites.md`.

Fixed links under doc/installation

---

doc/README.md

I suspect this section was in the root README before being moved here, because all the links were broken (more specifically, on the wrong level of the folder structure) and had to be replaced.

Fixed links in the quickstart README

---

doc/installation/README.md

Hello,
first of all tank you for this great project, truly amazing.  While trying to compile the project from source and following your instructions I have noticed a small typo in the readme. To my understanding  "without a non-Nvidia GPU" is a double negative and means the opposite of what is intended in the sentence.

Readme typo

---

scripts/osx/install_brew.sh

As suggested in https://github.com/CMU-Perceptual-Computing-Lab/openpose/runs/1699056384?check_suite_focus=true#step:6:20

(OSX) replace outdated ruby installer of brew

---

.github/root_index.html
.github/workflows/main.yml

Now the url can be reduced to [cmu-perceptual-computing-lab.github.io/openpose/](https://cmu-perceptual-computing-lab.github.io/openpose/)
I have tested it by manually adding the file to my `gh-pages` branch. See [matthijsburgh.github.io/openpose](https://matthijsburgh.github.io/openpose) So the file is correct, hopefully I made no mistakes in the procedure to copy the file.

Add root index.html so no need for crazy url for docs

---

src/openpose/net/bodyPartConnectorBaseCL.cpp

Fixes CMU-Perceptual-Computing-Lab/openpose#1879
Without the extra parens around `Type`, it is considered a function call. Because `Type` gets substitute with `float`, which is not a function and OpenCL does not have constructors for native types, this results in "error: expected expression."

Use `Type` as cast, not constructor.

---

src/openpose/calibration/cameraParameterEstimation.cpp

The function would compute the angle modulo 360, not 2pi as the function's name promises. Additionally, [fmod](https://en.cppreference.com/w/cpp/numeric/math/fmod) returns negative values if the argument is negative, which we also don't want. This can be fixed by adding 2pi to the argument - assuming the angle is not lower than -2pi.
This function is used in camera calibration, which is how I found the bug. OpenPose would mistakenly report that there are outliers in the angles, but this was due to `setAngleInRangeZeroTwoPi` not working properly.

Fix bugs in setAngleInRangeZeroTwoPi

---

doc/installation/1_prerequisites.md

Openpose is tested working correctly in driver 515.65 + CUDA 11.7.1 + cuDNN 8.5.0 albeit warnings unrelated due to in favour of C++17 instead of C++11.
Added a notice on the usage discouragement of cuDNN for Ubuntu 20.04 due to the performance degradation unresolved since Feb 2021. Refer https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1864#issuecomment-774706976
Dependencies to be installed completely thru script. Extra installation steps proved unnecessary thus removed.

Bump requirements for Ubuntu 20.04, added notice for cuDNN

---

src/openpose/pose/poseParameters.cpp

I've tried using the POSE_25B and encountered a "String(s) could not be found" error. This PR fixes it.

Fix wrong string declared in poseParameters.cpp
